# Make Matrices

1. [Upper Triangular](#Upper-Triangular-Matrix)
1. [Lower Triangular](#Lower-Triangular-Matrix)
1. [Diagonal](#Diagonal-Matrix)
1. [Symmetric](#Symmetric-Matrix)
1. [Anti-Symmetric](#Anti-Symmetric-Matrix)

In [1]:
import numpy as np

## Functions

Note thet these functions return arrays (`numpy.ndarray`) and not `numpy.matrix`.

In [2]:
def make_symmetric_matrix(diagonal=None, off_diagonal=None, antisymmetric=False):
    """
    Symmetric Matrix:      a[ij] = a[ji]
    Anti-Symmetric Matrix: a[ij] = -a[ji]
    For antisymmetric matrix, set: 
        antisymmetric = True
    """
    if diagonal is None:
        diagonal = (np.arange(5) + 1)*10
    diagonal = diagonal.flatten()
    if off_diagonal is None:
        off_diagonal = np.arange(2*diagonal.size)
    off_diagonal = off_diagonal.flatten()
    symmetry_factor = -1 if antisymmetric else 1        
    #assert 2*diagonal.size == off_diagonal.size
    if 2*diagonal.size == off_diagonal.size:
        shape = (diagonal.size, diagonal.size)
        sym = np.zeros(shape)
        # Fill up upper tringular section
        sym[np.triu_indices(shape[0], 1)] = off_diagonal.copy()
        # Fill up lower tringular section
        sym[np.tril_indices(shape[0], -1)] = off_diagonal.copy()*symmetry_factor
        # Fill the diagonal
        sym[np.diag_indices(shape[0])] = diagonal.copy()
        
        return sym

def make_diagonal_matrix(diagonal=None): 
    """
    Diagonal Matrix: all non-diagonal elements are zeros.
    """
    if diagonal is None:
        diagonal = (np.arange(5) + 1)*10
    diagonal = diagonal.flatten()
    shape = (diagonal.size, diagonal.size)
    diag = np.zeros(shape)
    # Fill the diagonal
    diag[np.diag_indices(shape[0])] = diagonal.copy()
    return diag
    
def make_triangular_matrix(diagonal=None, off_diagonal=None, matrix_type='upper'):
    """
    Upper Triangular Matrix: all elements below the diagonal are zeros.
    Lower Triangular Matrix: all elements above the diagonal are zeros.    
    """
    if diagonal is None:
        diagonal = (np.arange(5) + 1)*10
    diagonal = diagonal.flatten()
    if off_diagonal is None:
        off_diagonal = np.arange(2*diagonal.size)
    off_diagonal = off_diagonal.flatten()
    if 2*diagonal.size == off_diagonal.size:
        shape = (diagonal.size, diagonal.size)
        tri = np.zeros(shape)
        if matrix_type.lower() in ['upper', 'u']:
            # Fill up upper tringular section
            tri[np.triu_indices(shape[0], 1)] = off_diagonal.copy()
        if matrix_type.lower() in ['lower', 'l']:    
            # Fill up lower tringular section
            tri[np.tril_indices(shape[0], -1)] = off_diagonal.copy()
        # Fill the diagonal
        tri[np.diag_indices(shape[0])] = diagonal.copy()
        
        return tri

## Upper Triangular Matrix

In [3]:
make_triangular_matrix(diagonal=np.arange(1,6)*10, off_diagonal=np.arange(2*5)+10, matrix_type='upper')

array([[10., 10., 11., 12., 13.],
       [ 0., 20., 14., 15., 16.],
       [ 0.,  0., 30., 17., 18.],
       [ 0.,  0.,  0., 40., 19.],
       [ 0.,  0.,  0.,  0., 50.]])

## Lower Triangular Matrix

In [4]:
make_triangular_matrix(diagonal=np.arange(1,6)*10, off_diagonal=np.arange(2*5)+10, matrix_type='lower')

array([[10.,  0.,  0.,  0.,  0.],
       [10., 20.,  0.,  0.,  0.],
       [11., 12., 30.,  0.,  0.],
       [13., 14., 15., 40.,  0.],
       [16., 17., 18., 19., 50.]])

## Diagonal Matrix

In [5]:
make_diagonal_matrix(diagonal=np.arange(1,6)*10)

array([[10.,  0.,  0.,  0.,  0.],
       [ 0., 20.,  0.,  0.,  0.],
       [ 0.,  0., 30.,  0.,  0.],
       [ 0.,  0.,  0., 40.,  0.],
       [ 0.,  0.,  0.,  0., 50.]])

## Symmetric Matrix

In [6]:
make_symmetric_matrix(diagonal=np.arange(1,6)*10, off_diagonal=np.arange(2*5)+10, antisymmetric=False)

array([[10., 10., 11., 12., 13.],
       [10., 20., 14., 15., 16.],
       [11., 12., 30., 17., 18.],
       [13., 14., 15., 40., 19.],
       [16., 17., 18., 19., 50.]])

## Anti-Symmetric Matrix

In [7]:
make_symmetric_matrix(diagonal=np.arange(1,6)*10, off_diagonal=np.arange(2*5)+10, antisymmetric=True)

array([[ 10.,  10.,  11.,  12.,  13.],
       [-10.,  20.,  14.,  15.,  16.],
       [-11., -12.,  30.,  17.,  18.],
       [-13., -14., -15.,  40.,  19.],
       [-16., -17., -18., -19.,  50.]])